### PR TITLE
Db2

### PR DESCRIPTION
**Pull request by dvpravin**
Following are the updates in this pull request,

1) Created pax-jdbc-db2 module
2) Fixed issue found in pax-jdbc-oracle module - The createConnectionPoolDataSource method was passing incorrect class reference to setProperties method. Updated the reference from oracleXaDataSourceClass to oracleConnectionPoolDataSourceClass.

Regards,
Pravin

### CODE REVIEW

**Comment by j0xaf** [comment]
Hi Pravin,

may I ask what´s the difference with the DB2 driver merged yesterday?

Thanks & regards,
Jörn

**Comment by dvpravin** [comment]
Hi Jörn,

Last time when I checked for DB2 feature, it was not available, hence I developed it and created a pull request yesterday. I am not aware you too had developed DB2 feature and it is already merged to master branch. Looks like I was late to commit my changes by few days :-).

However you can review the other updates for Oracle feature and accept them if it looks correct.

Regards,
Pravin

**Comment by j0xaf** [comment]
Hi Pravin,

quite a coincidence that both of us worked on the DB2-feature at the same time. Sorry that I´ve been a small bit faster ;-)

As for the Oracle Commit: LGTM. Could you prepare a new PR with just that commit? Either I will merge it or @ANierbeck could grant you commit permissions so that you can merge it yourself. Afterall this is OPS4J :-)

Regards,
Jörn

**Comment by ANierbeck** [comment]
Hi, 

can can give you karma if you like, BUT we demand two things for PRs and sources to be committed. Very simple actually but, those are really necessary: 
1) create a Jira issue for the itch you scratched 
2) have a unit/integration test with it to show you got rid of that itch. 
that's it.
So in that case, we first would need a jira issue for it, second a new PR for it and after that I'll can give you karma if you like

regards, Achim

**Comment by dvpravin** [comment]
Thank you to both of you.

I will follow the steps provided by Achim and create a new pull request. I doubt if there are any unit tests for sub modules that has dependency on licensed versions of products like Oracle, MS, DB2 etc.

However will verify before committing.

Regards,
Pravin

**Pull request closed without merging**
