### PR TITLE
Support Jasypt property encryption.

### PR DESCRIPTION
**Pull request by damiri-ts**
See: https://ops4j1.jira.com/projects/PAXJDBC/issues/PAXJDBC-65

### CODE REVIEW

**Comment by damiri-ts** [comment]
@hwellmann @cschneider Hey guys, I would really appreciate some feedback on these changes. I certainly don't want to merge the pull request myself without a review from some regular contributors to the project.

Regards,

D

**Comment by damiri-ts** [comment]
Maybe it's the holidays? Maybe this project is not being maintained anymore? Is anyone out there?

**Comment by ANierbeck** [comment]
Hi, 
to me all minimum-requirements are met. 
It contains a jira issue attached to it, a test for verification and does seem to be an optional enhancement. 
looks good to me.

**Comment by damiri-ts** [comment]
@ANierbeck Thanks for the review :) It would have been nice to hear from some of the other contributors but maybe they are not around any more and it's been a week so I'm going to go ahead and merge.

**Pull request merged**
