### PR TITLE
HSQLDB DataSource

### PR DESCRIPTION
**Pull request by vincenzomazzeo**
[HSQLDB](http://hsqldb.org/) DataSource

The XA Data Source **isn't** supported and returns a SQLException.
The Pool Data Source **is** supported.

### CODE REVIEW

**Comment by vincenzomazzeo** [comment]
I've fixed the formatting. I hope it works now.

Thank you

**Comment by hwellmann** [comment]
I can't tell if it works, as there are no tests... Please have a look at the integration tests in pax-jdbc-itest as a starting point and add some to this PR. We'd better not integrate untested code.

Also please make sure to copy the Apache License header into your contributed sources, replacing the authors name with your own.

Thanks!

**Comment by vincenzomazzeo** [comment]
I was referring to the formatting. The DataSource works as I'm using it in production.

However I've added the Apache License header into my sources and the LICENSE file.

As soon as possible I'll add some tests.

Thank you!

**Comment by alexandreroman** [comment]
Hi @vincenzomazzeo,

Did you finally add tests to your pull request?
I am very interested in your contribution: I wish I could use HSQLDB with PAX-JDBC ;)

Thanks.

**Comment by hwellmann** [comment]
Alexandre, there's a big P for Participation in OPS4J. So if you see some value in this PR, instead of waiting for the author to finish it, you're welcome to add some tests of your own or build on the work that has been done so far.

Once the HSQLDB bundle looks ok and has reasonable test coverage, we're happy to merge it, or in fact we usually invite the author(s) to do the merge.

**Comment by vincenzomazzeo** [comment]
Hi Alexandre,

unfortunately I have not added tests. I hope to add them by the end of april. However as Harald said if you want to add some tests you're welcome.

Thank you and sorry for my delay.

**Comment by vincenzomazzeo** [comment]
Hi Harald,

I have finally added some integration tests.
Let me know if something is missing.

Thank you

**Comment by svogt** [comment]
I updated the PR, switched to the latest HSQLDB version and also switched to the native Pooled / XA Datasources of HSQLDB

**Pull request closed without merging**
