### PR TITLE
Added support for C3P0 connection pooling

### PR DESCRIPTION
**Pull request by assens**
created pax-jdbc-pool-c3p0 submodule

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hi 

first of all thank you for opening this pull request. 
It would be good if you could also open a corresponding Jira issue for this at https://ops4j1.jira.com/projects/PAXJDBC/issues

Now the hard part. 
Are you sure that we don't have a licence issue with this? 
As c3p0 is a LGPL licensed library and this code seems to be extending classes of it this isn't valid for using with a ASF2 licensed project. 

regards, Achim

**Comment by assens** [comment]
HI Achim, 
I've opened a JIRA ticket [PAXJDBC-83](https://ops4j1.jira.com/projects/PAXJDBC/issues/PAXJDBC-83)

C3P0 bundle is distributed by the Apache ServiceMix project, and that's the bundle used by the pax-jdbc-pool-c3p0. The C3p0PooledDataSourceFactory and C3p0XAPooledDataSourceFactory use only the com.mchange.v2.c3p0.DataSources factory class to create the DataSource pool.

There are no classes extending classes in the C3P0 library.

**Comment by ANierbeck** [comment]
Hi, 

thanks for the issue and the clarification, just wanted to make sure :-)


regards, Achim

**Comment by cschneider** [comment]
I think this should be merged now.

**Comment by cschneider** [comment]
This is already merged.

**Pull request closed without merging**
