### PR TITLE
Update to recent equinox 3.18.200

### PR DESCRIPTION
**Pull request by laeubi**

### CODE REVIEW

**Comment by laeubi** [comment]
@grgrzybek I think pax-jdbc do not really need to depend on such old OSGi standard?

**Comment by grgrzybek** [comment]
Pax JDBC 1.5.x is used in Karaf 4.2.x (and Fuse 7 based on Karaf 4.2) and these are still based on Felix 5 / OSGi Core 6.
Because only basic OSGi Core functionality is used (service registration), I'd keep it OSGi Core 1.8+ compatible. WDYT?

**Comment by laeubi** [comment]
Then I think we should probably use for the part where the API is required:

https://mvnrepository.com/artifact/org.osgi/osgi.core/4.3.1

instead of stick to an old equinox...

**Comment by grgrzybek** [comment]
With 0515d96 I've removed Equinox reference - it wasn't used anyway ;)

**Pull request closed without merging**
