### PR TITLE
PAXJDBC-156: Remove obsolete pax-jdbc-mssql module

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by laeubi** [comment]
Latest mssql driver already contains an implementation for JDBC Service, so you might want to check if pax-jdbc is really needed here anymore.

**Comment by graben** [comment]
I see this fix is almost one year old https://github.com/microsoft/mssql-jdbc/pull/700. Maybe it's time to remove it at all.

**Comment by graben** [comment]
mssql-jdbc is capable for OSGi DataSourceFactory for at least 3 stable releases (7.2, 7.4, 8.2) and works of course. If okay I will switch issue ticket to completely remove it from source.

**Comment by graben** [comment]
Hi @laeubi , @jbonofre
no responses. Should I merge?
Benjamin

**Comment by jbonofre** [comment]
LGTM thanks.

**Pull request merged**
