### PR TITLE
PAXJDBC-139: Add LocalTransaction support via pool-transx

### PR DESCRIPTION
**Pull request by graben**
This is linked to https://github.com/ops4j/org.ops4j.pax.transx/pull/15

### CODE REVIEW

**Comment by graben** [comment]
Hi @grgrzybek : Could you please have a look on this?

**Comment by grgrzybek** [comment]
@graben I'm thinking about checking "local" property from non-pool properties. What do you think? If you intend to take it from pool properties, please explain why. I'll merge and release then ;)
Thanks for the PR!

**Comment by graben** [comment]
@grgrzybek : I took pool property because it's a special feature of the pool (transx) implementation. I think no other pool does actually support this. But I'm fine to switch to non-pool properties, too.

**Comment by grgrzybek** [comment]
Thanks for the PR and sorry for this delay - I'll be releasing pax-jdbc 1.3.5 today (with pax-transx).

**Pull request merged**
