### PR TITLE
Added support for HikariCP connection pooling

### PR DESCRIPTION
**Pull request by antoniomaria**
Hi I would like to add support for HikariCP datasource, but I don't know the proper procedure to do it. Issue number etc,

### CODE REVIEW

**Comment by ANierbeck** [comment]
Hi, 

very easy, just open a JIRA issue here: 
https://ops4j1.jira.com/projects/PAXJDBC/issues

and make sure your commit message links to that jira issue. 

that's all

regards, Achim

**Comment by antoniomaria** [comment]
Thank you for the hint, i already created a jira account, and I got right to create an issue. I will create a issue for that.

**Comment by antoniomaria** [comment]
Unfortunately the pull request and the commit is done. I don't know how to change the commit message. Is it okey if I abandon the change and I do again?
Well honestly, I would like to test it a bit better and also get some feedback or suggestion about it.

**Comment by ANierbeck** [comment]
If you feel unsure about your pull-request and want to tweak it, go ahead and close it yourself.

**Comment by jvz** [comment]
You can amend the commit and force push.

On 17 December 2015 at 15:11, Antonio Maria Sanchez Berrocal <
notifications@github.com> wrote:

> Unfortunately the pull request and the commit is done. I don't know how to
> change the commit message. Is it okey if I abandon the change and I do
> again?
> Well honestly, I would like to test it a bit better and also get some
> feedback or suggestion about it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.jdbc/pull/11#issuecomment-165583212>
> .
>



-- 
Matt Sicker <boards@gmail.com>

**Comment by antoniomaria** [comment]
If you see my commit, I created a class called: HikariXAPooledDataSourceFactory and all methods throw MethodNotSupported Exception. I wonder if is okey, or is better to remove class?

**Comment by antoniomaria** [comment]
I just added a JUnit test for HikariPooledDataSourceFactory class

**Comment by antoniomaria** [comment]
It has been 3 months, since I committed this pull request. Any feedback, suggestions, improvement proposals?

**Comment by Delmonte3161** [comment]
It's been a while and I haven't seen an update to this.  I am also interested in the hikaricp additions.  Is this poll request dead or will it be incorporated at some point and if so when?

**Comment by ANierbeck** [comment]
oh ... sorry about that, must have missed the last changes. 
Thanks for providing the pull request and fixing the links

**Pull request merged**
