### PR TITLE
Test the main branch

### PR DESCRIPTION
**Pull request by laeubi**
# THIS IS JUST FOR TESTING

To see if the `main` branch work and the action do what is desired.

### CODE REVIEW

**Comment by laeubi** [comment]
@grgrzybek can you take a look why the test on the current `main` fails?

**Comment by grgrzybek** [comment]
@laeubi thanks for looking into Pax JDBC! I'll have a look next week - after Christmas/New Year holidays ;)

**Comment by laeubi** [comment]
> @laeubi thanks for looking into Pax JDBC! I'll have a look next week - after Christmas/New Year holidays ;)

No need to rush, I just wanted to make you aware of it as you are more familiar with the pax-jdbc karaf test :-)

**Comment by grgrzybek** [comment]
@laeubi Thanks for looking into this project.
The problem is that Pax Exam tests require the artifacts (here: 1.5.6-SNAPSHOT) to be available from actual Maven repository, but the build step doesn't `mvn install` them. Only `mvn package` i used). I'm not sure what are the best practices to handle such situation with Github Actions (I'd need some learning first about what can be done here...).

**Comment by laeubi** [comment]
Obsolete now

**Pull request closed without merging**
