### PR TITLE
PAXJDBC-122 - Classnotfound on tranql when using aries-jdbc

### PR DESCRIPTION
**Pull request by Tcharl**
Signed-off-by: charlie <cmordant1@gmail.com>

### CODE REVIEW

**Comment by Tcharl** [comment]
This is not really a formatting issue, I just variabilize some maven dependencies and added some within the 'dependencyManagement' section. I can do these things in two merge request if you want

**Comment by yogeshrao** [comment]
i think refactoring the maven dependencies and moving to dependencyManagement is right but i would suggest to do it as part of a different JIRA and have a  different PR for it.

I also see  change in source and target version to 1.8. if all agree to toggle to JDK 1.8 then there are few dependency versions which should also change.

**Comment by cschneider** [comment]
What is the status of this PR? I see no more activity on this since April. @Tcharl are you planning to work on this?

**Comment by Tcharl** [comment]
I thought it was ok.
I didn't think it was a blocker and waited for one Ops4j commiter to merge it.

What should I do?

**Comment by jbonofre** [comment]
It would be great to revive this PR and rebase. Then I will do a new pass on it.

**Comment by laeubi** [comment]
@Tcharl is this still relevant for you?

**Comment by Tcharl** [comment]
I'm sorry but I no longer use pax-jdbc (and since a bit of time now), I may use it one day again who knows...
If someone want to takeover this PR feel free to do so, otherwise feel free to close it

**Comment by grgrzybek** [comment]
Thanks for feedback. Closing.

**Pull request closed without merging**
