### PR TITLE
[PAXJDBC-144] Build pax-jdbc-mssql against offical driver

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by grgrzybek** [comment]
@graben thanks for the PR - give me 1, 2 days to review and merge - this time I promise it'll be quicker ;)

**Comment by jbonofre** [comment]
I gonna take a look as well.

**Comment by graben** [comment]
@grgrzybek @jbonofre 
Thanks, it maybe worth to have a look why feature verify does not work for several features.

**Comment by grgrzybek** [comment]
It worked not so long time ago ;)
I'll check it - leave it to me.

regards
Grzegorz Grzybek

pon., 17 cze 2019 o 14:19 Benjamin Graf <notifications@github.com>
napisał(a):

**Comment by grgrzybek** [comment]
@graben thanks - I added jta bundle to pax-jdbc-mssql feature and it verifies correctly.

**Comment by graben** [comment]
@grgrzybek great, know I know what was missing :)

**Pull request merged**
