### PR TITLE
PAXJDBC-125 - allowed setting xa config as false. it now throws

### PR DESCRIPTION
**Pull request by yogeshrao**
Allow setting xa=false in datasource config file. ConfigurationException is thrown if set to anything other than true or false.

### CODE REVIEW

**Comment by ANierbeck** [comment]
Just invited you to the team, so you can merge your PR yourself. 
Welcome aboard :)

**Comment by cschneider** [comment]
How about using Boolean.parseBoolean(astring);

**Comment by yogeshrao** [comment]
Boolean.parseBoolean(astring) can work, just couple of observations  
1. Does not have a predefined set to qualify for false as any value which isnt "True" is considered false
2. On using API we will have to place a check for "false" anyways
3. through exception if anyother value is found

since its predefined values which we support a string compare should be fine.

**Comment by cschneider** [comment]
Sounds good. If you considered it and have good reasons for not using it that is fine.

**Comment by yogeshrao** [comment]
merged, the JIRA needs to be updated and closed. I dont think so i have rights to close the issue.

**Comment by ANierbeck** [comment]
we can fix that ...

**Comment by ANierbeck** [comment]
... you should have the appropriate rights now :)

**Comment by yogeshrao** [comment]
Works ! Thank you...

**Pull request merged**
